// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package simple_bank

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
